### ISSUE TITLE
Crash on startup without sully's mod

### ISSUE THREAD

**Issue by crimson-bear** [thelegitdolt/dolt-mod-how#1]
[crash-2024-09-22_19.21.05-client.txt](https://github.com/user-attachments/files/17091647/crash-2024-09-22_19.21.05-client.txt)

**Comment by thelegitdolt** [comment]
oopsies

**Comment by thelegitdolt** [comment]
sorry, 1.19.2 is no longer supported but the 1.20 version doesn't depend on sully's mod anymore! so that's something
