### ISSUE TITLE
Modrinth Page doesnt credit me wtf

### ISSUE THREAD

**Issue by Carmenboy1** [thelegitdolt/dolt-mod-how#2]
i cant believe dolt would _**STEAL**_ art from me!!!! _(Modrinth Account is CarmenTheFungus)_

### NOW DO IT!!!!!11!

**Comment by thelegitdolt** [comment]
😭😭😭😭

**Comment by thelegitdolt** [comment]
i did it yay

**Comment by thelegitdolt** [comment]
fuck
