### ISSUE TITLE
I updated DMH and it fails to load.

### ISSUE THREAD

**Issue by MythicHH** [thelegitdolt/dolt-mod-how#3]
DMH failed to load when I updated it to v2.1.0. 
[Mod list](https://pastebin.com/ff1dXtuC)
[Crash log](https://mclo.gs/w9fI78Q)

**Comment by thelegitdolt** [comment]
i'm sorry i was mean to you mystic but yes reporting on git is much better than reporting in dms <3

**Comment by MythicHH** [comment]
it's fine, if I have any other issues I will report them here as well
