### ISSUE TITLE
Mixin related crash with Farmers Delight

### ISSUE THREAD

**Issue by SocialNyetwork** [thelegitdolt/dolt-mod-how#6]
[crash-2024-12-17_11.14.29-fml.txt](https://github.com/user-attachments/files/18170342/crash-2024-12-17_11.14.29-fml.txt)

**Comment by thelegitdolt** [comment]
crash jumpscare

**Comment by thelegitdolt** [comment]
pray send latest.log, I can run perfectly with FD

**Comment by thelegitdolt** [comment]
Okay so this crash is only since you don't have My Nether's Delight installed. I will work on a fix but if you are really into the game not crashing you can just install that for now

**Comment by thelegitdolt** [comment]
actually i just fixed it so the update will be out now

**Comment by thelegitdolt** [comment]
hey are you able to use the mod now? did the newest update fix this

**Comment by SocialNyetwork** [comment]
Yes, it is now working without issue. Thank you!

**Comment by thelegitdolt** [comment]
glad to hear!
